### ISSUE TITLE
Jade has been renamed to Pug.

### ISSUE THREAD

**Issue by DomtronVox** [jstransformers/jstransformer-jade#12]
FYI, installing this package now has warnings because Jade was forced to rename their project.
See https://github.com/pugjs/pug/issues/2184 for reference. 

I got an error when trying to install, but I think it was unrelated to this. It appears that jstransformer-pug already exists so perhaps put a warning in the README about the name change?

Thanks for your work on building maintaining this repo. :)

**Comment by ForbesLindesay** [comment]
Done
